### ISSUE TITLE
No such file or directory: '/home/wang/miniconda3/envs/museformer/lib/python3.8/site-packages/midiprocessor/key_profile.pickle

### ISSUE THREAD

**Issue by WxhKeepFighting** [btyu/MidiProcessor#1]
when I used it to process the LMD-full dataset, I met the error that 'FileNotFoundError: [Errno 2] No such file or directory: '/home/wang/miniconda3/envs/museformer/lib/python3.8/site-packages/midiprocessor/key_profile.pickle'', and I do not find key_profile.pickle in this dir, so what can I do to fix this error.

**Comment by btyu** [comment]
Sorry, a bug. Now it is fixed, and you may reinstall the package. Thanks.
